baseURL = "https://itachi.xyz"
languageCode = "zh-CN"
title = "itachi's Blog"
#theme = "maupassant-hugo"
googleAnalytics = ""  # UA-XXXXXXXX-X

## 保持分类的原始名字（false会做转小写处理）
preserveTaxonomyNames = true
## 是否禁止URL Path转小写
disablePathToLower = false

hasCJKLanguage = true
summaryLength = 50

disqusShortname = ""  ## 是否开启disqus评论，不要和utteranc同时开启

[author]
  name = "阿林"

[params]
  author = "阿林"
  subtitle = "昨夜梦 今辰你 明日思 | Blog about life and learning."
  keywords = "Blog"
  description = "这是阿林的博客"
  busuanzi = true #启用不算子网页统计
  googleAd = ""  #ca-pub-xxxxxxxxxxxxxx
  localSearch = true # 启用本地搜索

  # 这里我存放在了主题的static文件夹里，根目录的似乎也可以
  # customCSS = ['douban.css', 'other.css']
  # if ['custom.css'], load '/static/css/custom.css' file
  # customJS = ['douban.js']
  # if ['custom.js'], load '/static/js/custom.js' file

  # 全局开关，你也可以在每一篇内容的 front matter 中针对单篇内容关闭或开启某些功能
  toc = false  # 是否开启目录

## 友情链接，可以多个

[[params.links]]
  title = "AC的简单博客"
  name = "AC的简单博客"
  url = "https://www.acdiao.com"
  
[[params.links]] 
  title = "AC大佬的图床"
  name = "AC大佬的图床"
  url = "https://img.tujidu.com"

[[params.links]]
  title = "记录实验过程"
  name = "记录实验过程"
  url = "https://blog.cetcweb.cn/"

[[params.links]]
  title = "奇它博客"
  name = "奇它博客"
  url = "https://qitablog.com/"
  
[[params.links]]
  title = "Ezio"
  name = "Ezio"
  url = "http://laihongquan.com/"
  
[[params.links]]
  title = "早起的年轻人"
  name = "早起的年轻人"
  url = "https://luckly.work/"
[[params.links]]
  title = "格姗知识圈"
  name = "格姗知识圈"
  url = "https://geshanzsq.com"

[params.utteranc]
  enable = false
  repo = "your github repo" ##换成自己得
  issueTerm = "pathname"
  theme = "github-light"
  
[params.gittalk]
  enable = true
  owner="itachi1912"
  repo="itachi1912.github.io"
  clientID="30ffb17e5ccaa5f1830e"
  clientSecret="67ba9ccd9df5c8f402f46b2462f09d644219c04f"


## 开启版权声明，协议名字和链接都可以换
[params.cc]
    name = "知识共享署名-非商业性使用-禁止演绎 4.0 国际许可协议"
    link = "https://creativecommons.org/licenses/by-nc-nd/4.0/"

## 配置代码高亮
[markup]
  [markup.highlight]
    lineNos = false
    style = "monokai"

## 配置网站菜单

[menu]

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 3

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 1

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 2

  [[menu.main]]
    identifier = "oneNote"
    name = "一言"
    url = "/oneNote/"
    weight = 5

